In [1]:
%pip install -U numpy pandas matplotlib seaborn scikit-learn

Requirement already satisfied: numpy in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (2.4.2)
Requirement already satisfied: pandas in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: matplotlib in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: seaborn in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /home/weblov3/ml-course-homeworks/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
ls

hw01_setup_tools.ipynb  README.md  Untitled.ipynb

In [4]:
cd ..

/home/weblov3/ml-course-homeworks

In [5]:
ls

hw01_setup_tools/  ml_dataset_20k.csv  requirements.txt  scooter_alerts.ipynb

In [6]:
df = pd.read_csv("ml_dataset_20k.csv")

In [7]:
df.head()

,incident_id,probability,is_real_incident,last_order_end,after_order_start,gap_minutes,total_after_distance_km,max_jump_distance_km,mean_speed_kmh,median_speed_kmh,...,bearing_changes,static_segments_ratio,radius_from_start_m,coordinate_stability_m,return_count,after_order_start_hour,after_track_duration_minutes,bearing_changes_ratio,full_stop_count,linearity
0,25744,70,0,0001-01-01T00:00:00,2025-03-10T01:12:28.299000,1.064619e+09,1.124,0.135,0.08,0.04,...,147,0.992,355.60,68.09,482,1,1087.73,0.248,561,0.316
1,25743,0,0,0001-01-01T00:00:00,2025-03-10T18:12:55.712000,1.064620e+09,0.022,0.002,0.46,0.02,...,13,0.973,2.55,0.91,36,18,67.21,0.361,34,0.108
2,25741,70,0,0001-01-01T00:00:00,2025-03-10T16:36:27.604000,1.064620e+09,2.635,0.571,37.35,0.18,...,11,0.776,807.81,227.19,46,16,162.25,0.131,65,0.030
3,25740,70,0,0001-01-01T00:00:00,2025-03-10T12:00:00.595000,1.064620e+09,5.898,0.490,0.90,0.26,...,33,0.872,435.53,131.13,141,12,437.85,0.169,171,0.013
4,25739,0,0,0001-01-01T00:00:00,2025-03-10T19:06:51.672000,1.064621e+09,0.252,0.237,74.77,0.16,...,4,0.875,239.35,74.19,0,19,8.06,0.571,4,0.951

In [8]:
df.shape

(5938, 21)

In [9]:
df.describe()

,incident_id,probability,is_real_incident,gap_minutes,total_after_distance_km,max_jump_distance_km,mean_speed_kmh,median_speed_kmh,max_speed_kmh,bearing_changes,static_segments_ratio,radius_from_start_m,coordinate_stability_m,return_count,after_order_start_hour,after_track_duration_minutes,bearing_changes_ratio,full_stop_count,linearity
count,5938.000000,5938.000000,5938.000000,5.938000e+03,5938.00000,5938.000000,5.938000e+03,5938.000000,5.938000e+03,5938.000000,5938.000000,5.938000e+03,5.938000e+03,5938.000000,5938.000000,5938.000000,5938.000000,5938.000000,5938.000000
mean,22135.107107,19.676659,0.097676,1.064618e+09,537.55116,63.966336,5.146006e+03,88.773361,4.342568e+05,25.538565,0.706717,6.330878e+04,1.192029e+04,98.202930,14.665207,363.610369,0.166752,145.542270,0.329145
std,2109.704114,28.830670,0.296901,1.247905e+03,2376.51252,566.368036,1.710007e+05,4105.047338,1.928209e+07,43.420595,0.312425,5.663727e+05,1.119326e+05,201.471605,5.570387,503.562957,0.186371,228.653561,0.373067
min,18161.000000,0.000000,0.000000,1.064614e+09,0.00000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20486.250000,0.000000,0.000000,1.064617e+09,0.20725,0.081000,2.600000e-01,0.000000,7.815000e+00,1.000000,0.500000,1.488275e+02,2.806500e+01,2.000000,12.000000,11.267500,0.028000,3.000000,0.014000
50%,22192.500000,0.000000,0.000000,1.064618e+09,3.31750,0.839000,3.780000e+00,0.030000,5.948500e+01,7.000000,0.833000,1.181050e+03,3.063000e+02,8.000000,16.000000,130.150000,0.118000,24.000000,0.125000
75%,23935.750000,45.000000,0.000000,1.064619e+09,235.07725,30.493000,9.459250e+01,2.142500,1.490990e+03,31.000000,0.977750,3.075978e+04,8.982688e+03,93.000000,18.000000,514.405000,0.235000,198.000000,0.671750
max,25744.000000,75.000000,1.000000,1.064621e+09,77653.09100,8347.678000,7.981810e+06,281538.460000,1.251772e+09,456.000000,1.000000,8.345132e+06,3.736607e+06,2582.000000,23.000000,2157.340000,1.000000,1247.000000,1.000000

In [10]:
df.isna().sum()

incident_id                     0
probability                     0
is_real_incident                0
last_order_end                  0
after_order_start               0
gap_minutes                     0
total_after_distance_km         0
max_jump_distance_km            0
mean_speed_kmh                  0
median_speed_kmh                0
max_speed_kmh                   0
bearing_changes                 0
static_segments_ratio           0
radius_from_start_m             0
coordinate_stability_m          0
return_count                    0
after_order_start_hour          0
after_track_duration_minutes    0
bearing_changes_ratio           0
full_stop_count                 0
linearity                       0
dtype: int64